### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by capveg-netdebug** [ohadravid/netstat2-rs#12]
Some easy bug fixes are sitting in queue and easy questions in the issues.  Let me know if there's a better repo for this.

ATTN: @ohadravid , @chengyuhui , @koushiro , @shekohex 

ATTN: @shinmao, @payn  (recent questions and bug fixers)

**Comment by shekohex** [comment]
Sorry I have no idea, I just made a contribution long time ago. You should look for alternative if doesn't work for you, and tag rustsec team, maybe?

**Comment by ohadravid** [comment]
Hi @capveg-netdebug 🙂 

This project isn't being actively maintained, but I'm happy to accept PRs with fixes and improvements.

As with any open source stuff, I might be a little slow to response 🐢
