### ISSUE TITLE
build failed: cannot find type `proc_fdinfo` in this scope

### ISSUE THREAD

**Issue by lemos1235** [ohadravid/netstat2-rs#20]
I got error in macos m1

error message: 
error[E0412]: cannot find type `proc_fdinfo` in this scope
   --> /Users/lg/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/netstat2-0.11.0/src/integrations/osx/netstat.rs:222:36
    |
222 |     fn try_from_proc_fdinfo(other: proc_fdinfo) -> Result<Self, Error> {
    |                                    ^^^^^^^^^^^ not found in this scope

**Comment by ohadravid** [comment]
Hi. I can run the example from the README locally on macOS using:

```toml
[dependencies]
netstat2 = "0.11"
```

so I suspect this is an environment issue.

Can you try to minimize this? It's possible this is related to the new `bindgen` integration.

Can you check if `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/` exists and that `#include <libproc.h>` works in a clang? (This is from the `build.rs` of this crate)

**Comment by lemos1235** [comment]
bindgen = 0.65 not work, bindgen = "0.69" is ok

**Comment by ohadravid** [comment]
Nice! Let me know if the new version works as well 🚀
