### ISSUE TITLE
Unsound implementation of `next` leading to misaligned pointer dereference

### ISSUE THREAD

**Issue by shinmao** [ohadravid/netstat2-rs#9]
https://github.com/ohadravid/netstat2-rs/blob/b3c7d2098623989c5556bf68b5121f2ea1dc1b5b/src/integrations/linux/netlink_iterator.rs#L54-L66
At line 60, the code casted u8 to larger-aligned type (we could tell it was u32 because `repr(C)` made the struct's layout stable), which created a misaligned pointer. At line 67, the code made a dereference. Misaligned pointer dereference would lead to undefined behavior and we should avoid it.

**Comment by ohadravid** [comment]
Fixed in #19, thanks @shinmao 🫡
